# Generated by BoostInstall.cmake for boost_numpy-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_numpy38 1.77.0 EXACT)

include("${CMAKE_CURRENT_LIST_DIR}/boost_numpy-targets.cmake")
