# Generated by BoostInstall.cmake for boost_numpy38-1.77.0

include(CMakeFindDependencyMacro)

find_dependency(boost_config 1.77.0 EXACT)
find_dependency(boost_core 1.77.0 EXACT)
find_dependency(boost_detail 1.77.0 EXACT)
find_dependency(boost_mpl 1.77.0 EXACT)
find_dependency(boost_python 1.77.0 EXACT)
find_dependency(boost_smart_ptr 1.77.0 EXACT)
find_dependency(Python COMPONENTS NumPy)

include("${CMAKE_CURRENT_LIST_DIR}/boost_numpy38-targets.cmake")
